### PR TITLE
adding button UI for changing plot colors

### PR DESCRIPTION
**Pull request by jaybee84**
added in a few color buttons using `plotly` for initial testing.

### CODE REVIEW

**Comment by andrewelamb** [comment]
@jaybee84 I see the buttons, but they don't seem to do anything.

**Comment by jaybee84** [comment]
Hey @andrewelamb ... sorry I missed responding to this earlier.  It seems like the change is passing all the tests and technically should work, but I think it may be getting overridden by something in another function somewhere. 
My first hunch was that it was being overridden by sage_themes(), so I tried plotting without sage_themes() but saw that the plots were still showing sage_themes() even when I commented it out of the plot function. Do you know if there is another function that is influencing the plot func?

**Comment by andrewelamb** [comment]
@jaybee84 Nothing comes to mind right away. I'll need to look into it some more.

**Comment by andrewelamb** [comment]
@jaybee84 I've played with this a little bit but can't figure it out. 

` list(method = "restyle",
           args = list("fill", "Rainbow"),
           label = "Rainbow"),`

My guess is fill is the wrong term here. Fill is what ggplot2 calls the color inside the bars, but you need the plotly name.

**Comment by andrewelamb** [comment]
@jaybee84 I'm going to close this for now. Feel free to reopen if a fix becomes available!

**Pull request closed without merging**
